# fly.toml app configuration file generated for fivem-weed-discord-bot on 2024-02-27T23:08:57+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fivem-weed-discord-bot'
primary_region = 'cdg'

[build]

[[vm]]
  size = 'shared-cpu-1x'
